spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/postgres"
    username: "postgres"
    password: "postgres"
    pool-size: 5
  liquibase:
    change-log: db/changelog/db.changelog-master.xml

logging:
  level:
    org.springframework: DEBUG
#    tech.romashov: DEBUG
#  pattern:
#    file: %d %p %c{1.} [%t] %m%n
#    console: %d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n
#  file: web.log

server:
  error:
    include-stacktrace: never
