language: java
jdk:
  - oraclejdk8
dist: trusty
services:
  - xvfb
before_cache:
  - rm -f  .gradle/caches/modules-2/modules-2.lock
  - rm -fr .gradle/caches/*/plugin-resolution/
cache:
  directories:
    - .gradle/caches/
install:
  - ./gradlew --version
  - ./gradlew assemble --info
script:
  - xvfb-run --server-args="-screen 0 1024x768x24" ./gradlew test

notifications:
  email: false
