#app:
#  datasource:
#    url: "jdbc:h2:mem:mydb"
#    username: "sa"
#    pool-size: 30
app:
  datasource:
    url: "jdbc:postgresql://localhost:5432/postgres"
    username: "postgres"
    password: "postgres"
    pool-size: 30
