/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tech.romashov.dale.application;

import org.junit.Test;

import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.Matchers.equalTo;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        App classUnderTest = new App();
        assertThat(classUnderTest.getGreeting(), equalTo("Hello world."));
    }
}
