/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tech.romashov.dale.application;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

import java.util.Collections;

@SpringBootApplication
public class App {
    private static final Logger log = LoggerFactory.getLogger(App.class);

    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        App app = new App();
        SpringApplication application = new SpringApplication(App.class);
        application.setDefaultProperties(Collections.singletonMap("server.port", app.port()));
        application.run(args);
    }

    public String port() {
        if (System.getenv("PORT").equals("") || System.getenv("PORT") == null) {
            return "8081";
        } else {
            return System.getenv("PORT");
        }
    }
}
